- type: entity
  parent: [ SimpleMobBase, MobCombat ]
  id: BaseTerrorSpider
  name: terror spider
  description: Deadly hybrid of a giant spider and xenomorph.
  abstract: true
  components:
#  - type: ThermalVision
  - type: Sprite
    drawdepth: Mobs
    layers:
    - map: ["enum.DamageStateVisualLayers.Base", "movement"]
      state: alive
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.45
        density: 190
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: DamageStateVisuals
    states:
      Alive:
        Base: alive
      Critical:
        Base: dead
      Dead:
        Base: dead
  - type: Butcherable
    spawned:
    - id: FoodMeatSpiderLeg
      amount: 3
  - type: CombatMode
  - type: Body
    prototype: AnimalHemocyanin
  - type: Damageable
    damageContainer: Biological
    damageModifierSet: TerrorSpider
  - type: MobThresholds
    thresholds:
      0: Alive
      90: Dead
  - type: MeleeWeapon
    altDisarm: false
    hidden: true
    angle: 0
    animation: WeaponArcClaw
    soundHit:
      path: /Audio/Weapons/Xeno/alien_claw_flesh3.ogg
    damage:
      types:
        Piercing: 18
  - type: SolutionContainerManager
    solutions:
      melee:
        maxVol: 5
  - type: SolutionRegeneration
    solution: melee
    generated:
      reagents:
      - ReagentId: Mechanotoxin
        Quantity: 1
  - type: MeleeChemicalInjector
    transferAmount: 0.25
    solution: melee
  - type: NoSlip
  - type: Spider
  - type: IgnoreSpiderWeb
  - type: Bloodstream
    bloodReagent: CopperBlood
    bloodlossDamage:
      types:
        Bloodloss:
          0.05
    bloodlossHealDamage:
      types:
        Bloodloss:
          -1
  - type: Speech
    speechVerb: Arachnid
    speechSounds: Arachnid
    allowedEmotes: ['Click', 'Chitter']
  - type: Vocal
    sounds:
      Male: UnisexArachnid
      Female: UnisexArachnid
      Unsexed: UnisexArachnid
  - type: LanguageSpeaker
    currentLanguage: Spider
  - type: LanguageKnowledge
    speaks:
    - Xeno
    understands:
    - TauCetiBasic
    - Xeno
  - type: TypingIndicator
    proto: spider
  - type: Tag
    tags:
    - DoorBumpOpener
    - FootstepSound
  - type: Prying
    pryPowered: true
    force: true
    speedModifier: 1.5
    useSound:
      path: /Audio/Items/crowbar.ogg
  - type: PassiveDamage 
    allowedStates:
    - Alive
    damageCap: 89
    damage:
      types:
        Poison: -0.07
      groups:
        Brute: -0.07
        Burn: -0.07
  - type: NpcFactionMember
    factions:
      - Xeno
  - type: InputMover
  - type: MobMover
  - type: HTN
    rootTask:
      task: SimpleHostileCompound
  - type: GhostTakeoverAvailable
  - type: GhostRole
    makeSentient: true
    name: ghost-role-terror-spider-name
    description: ghost-role-terror-spider-description
    rules: ghost-role-terror-spider-rules
    raffle:
      settings: short
  - type: Puller
    needsHands: false
  - type: Stamina
    excess: 250
  - type: ActionGrant
    actions:
    - ActionEggInjection
  - type: GuideHelp
    guides:
    - TerrorSpiders
